# Generated by Django 5.0 on 2025-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='session_key'),
        ),
        migrations.AddIndex(
            model_name='fieldrecord',
            index=models.Index(fields=['booked_user_id', 'status'], name='course_fiel_booked__a12eae_idx'),
        ),
    ]
