# Generated by Django 5.0 on 2025-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_myuser_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_icons/', verbose_name='头像'),
        ),
    ]
