# Generated by Django 5.0 on 2025-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_fieldrecord"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fieldrecord",
            index=models.Index(fields=["date"], name="course_fiel_date_6beaf5_idx"),
        ),
    ]
