# Generated by Django 5.0 on 2025-05-15 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_myuser_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrecord',
            name='matching_min_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='fieldrecord',
            name='matching_order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldrecord',
            name='matching_payment_type',
            field=models.IntegerField(blank=True, choices=[(1, '平摊'), (2, '个人承担')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='fieldrecord',
            name='matching_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_field_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldrecord',
            name='booked_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_field_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
