# Generated by Django 5.0 on 2025-05-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_fieldrecord_course_fiel_date_6beaf5_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldrecord',
            old_name='value',
            new_name='price',
        ),
    ]
