# Generated by Django 5.0 on 2025-05-17 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_fieldrecord_matching_min_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrecord',
            name='matched_order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldrecord',
            name='matched_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_field_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldrecord',
            name='matching_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_field_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
