# Generated by Django 5.0 on 2025-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_value_fieldrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Booked'), (3, 'Matching'), (4, 'Matched')], default=1),
        ),
    ]
