# Generated by Django 5.0 on 2025-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_fieldrecord_booked_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrecord',
            name='booked_order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
