# Generated by Django 5.0 on 2025-05-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_fieldrecord_booked_order_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
